name: Unit Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'dist/**'
      - tsconfig.json
      - package.json
      - yarn.lock

jobs:
  jest:
    name: Test with jest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Jest
        run: yarn run test
